export const ShopRoute = '/shop'
export const HomeRoute = '/'
export const RegisterRoute = '/register' 
export const AuthRoute = '/authentication'
export const ContactRoute = '/contact'
export const NewsRoute = '/news'
export const LOCAL_API_URL = 'http://forial-server-production.up.railway.app/api'